[project]
name = "mlem-method"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "captum>=0.8.0",
    "exca>=0.3.0",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
    "joblib-progress>=1.0.6",
    "loguru>=0.7.3",
    "matplotlib>=3.10.1",
    "nbformat>=5.10.4",
    "pandas>=2.2.3",
    "parametrization-cookbook>=0.18",
    "pingouin>=0.5.5",
    "plotly>=6.0.1",
    "pydantic>=2.11.1",
    "pytest>=8.3.5",
    "scikit-learn>=1.6.1",
    "scipy>=1.15.2",
    "seaborn>=0.13.2",
    "sqlmodel>=0.0.24",
    "torch>=2.6.0",
    "torchsort>=0.1.9",
    "torchvision>=0.21.0",
    "tqdm>=4.67.1",
    "transformers>=4.50.1",
    "turm>=0.7.3",
    "umap-learn>=0.5.7",
    "wandb>=0.19.8",
    "xarray>=2025.3.0",
]

[tool.pytest.ini_options]
pythonpath = ["./"]
